var myString;
var myNum;
var myBool;
var myVar;
/*
let strArr: string[];
let numArr: number[];
let boolArr: boolear[];
*/
var strArr;
var numArr;
var boolArr;
var stringNumTuple;
myString = 'Hello'.slice(0, 3);
myNum = 1;
myBool = true;
myVar = 5;
strArr = ['Hello', 'World'];
numArr = [1, 2, 3];
boolArr = [true, false, true];
stringNumTuple = ['Hello', 4];
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
console.log(myString);
console.log(myNum);
console.log(myBool);
console.log(myVar);
console.log(strArr);
console.log(numArr);
console.log(boolArr);
console.log(stringNumTuple);
console.log(myVoid);
